name: Forget Feedback

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/**
      - forget-feedback/**
  pull_request:
    paths:
      - .github/workflows/**
      - forget-feedback/**

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: forget-feedback/testapp
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: npm ci
      - run: npx playwright install
      - run: npm run test:e2e
