name: Forget (Rust)

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/**
      - forget/crates/**
      - forget/Cargo.*
      - forget/*.toml
  pull_request:
    paths:
      - .github/workflows/**
      - forget/crates/**
      - forget/Cargo.*
      - forget/*.toml

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Rust Test (${{ matrix.target.os }})
    strategy:
      matrix:
        target:
          - target: ubuntu-latest
            os: ubuntu-latest
          # TODO: run on more platforms
          # - target: macos-latest
          #   os: macos-latest
          # - target: windows-latest
          #   os: windows-latest
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v3
      - name: cargo test
        working-directory: forget
        run: cargo test --manifest-path=Cargo.toml --locked ${{ matrix.target.features && '--features' }} ${{ matrix.target.features }}

  lint:
    name: Rust Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          # NOTE: use `rustup run <toolchain> <command>` in commands below
          # with this exact same toolchain value
          toolchain: nightly-2023-08-01
          override: true
          components: rustfmt, clippy
      - name: rustfmt
        run: grep -r --include "*.rs" --files-without-match "@generated" crates | xargs rustup run nightly-2023-08-01 rustfmt --check --config="skip_children=true"
        working-directory: ./forget/
      # - name: cargo clippy
      #   working-directory: forget
      #   run: rustup run nightly-2023-08-01 cargo clippy -- -Dclippy::correctness

  build:
    name: Rust Build
    runs-on: ubuntu-latest
    # TODO: build on more platforms, deploy, etc
    steps:
      - uses: actions/checkout@v3
      - name: cargo build
        working-directory: forget
        run: cargo build --release
