name: Forget (TypeScript)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  discover_yarn_workspaces:
    name: Discover yarn workspaces
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "matrix=$(find forget/packages -mindepth 1 -maxdepth 1 -type d | sed 's!forget/packages/!!g' | tr '\n' ',' | sed s/.$// | jq -Rsc '. / "," - [""]')" >> $GITHUB_OUTPUT

  # Hardcoded to improve parallelism for babel-plugin-react-forget
  lint:
    name: Lint babel-plugin-react-forget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: forget/yarn.lock
      - name: Restore cached node_modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.arch }}-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
        working-directory: forget
      - run: yarn workspace babel-plugin-react-forget prettier:ci
        working-directory: forget
      - run: yarn workspace babel-plugin-react-forget lint
        working-directory: forget

  # Hardcoded to improve parallelism for babel-plugin-react-forget
  jest:
    name: Jest babel-plugin-react-forget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: forget/yarn.lock
      - name: Restore cached node_modules
        uses: actions/cache@v3
        id: node_modules
        with:
          path: "**/node_modules"
          key: ${{ runner.arch }}-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
        working-directory: forget
      - run: yarn workspace babel-plugin-react-forget jest
        working-directory: forget

  test:
    name: Test ${{ matrix.workspace_name }}
    needs: discover_yarn_workspaces
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        workspace_name: ${{ fromJSON(needs.discover_yarn_workspaces.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: forget/yarn.lock
      - name: Restore cached node_modules
        uses: actions/cache@v3
        id: node_modules
        with:
          path: "**/node_modules"
          key: ${{ runner.arch }}-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
        working-directory: forget
      - run: yarn workspace ${{ matrix.workspace_name }} test
        working-directory: forget
