[package]
name = "swc-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_common = { version = "0.31.12", features = ["tty-emitter", "sourcemap", "anyhow"] }
swc_core = "0.78.15"
swc_ecma_parser = "0.136.2"
swc_ecma_transforms_base = "0.129.8"
swc_ecma_visit = "0.92.1"
swc_visit = "0.5.6"
