[package]
name = "hir-optimization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
estree = { path = "../estree" }
hir = { path = "../hir" }
hir-ssa = { path = "../hir-ssa" }
build-hir = { path = "../build-hir" }
utils = { path = "../utils" }
bumpalo = "3.13.0"
indexmap = "2.0.0"
miette = { version = "5.9.0" }
thiserror = "1.0.41"